### ISSUE TITLE
`slather()` needs access to the `frosting` object

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/epipredict#108]
Refactor `slather()` throughout so that it takes `the_frosting` as an argument.

We may actually need access to the layers we create.

On further thought, it may be better to make the signature `slather(object, components, the_workflow,...)` so that it has access to everything (rather than `the_recipe` `the_fit` and `the_frosting` separately).

**Comment by rachlobay** [comment]
Based on the ~July 6 discussion about this on Components conundrum doc, the `time_value` from `components$keys` is currently being used for both forecast_date and test_date defaults. If you want the non-forged test data to be used instead, it still does not look to be currently available in components, as I think you noted. For reference, I will post the ex. from that doc below to show what is available in components for the `layer_add_forecast_date` test (it looks like the molded training data and the forged test data parts are there). If that is the case, components does not look to have what we need. So what is the best way to get the original test data? Has there been something new introduced that would make this a piece of cake because right now, it isn’t clear that `object`, `components`, `the_recipe`, or `the_fit` contains it… And even if we included `the_frosting` in `slather(), would that contain the test data that is just inputted in `predict()`?  I am not sure about that, so let me know if it does…. Likewise for `the_workflow`. 

We could always revert these back to what I had a long time ago and have the user input the (non-forged) test data into the layer directly as an argument, but I’d have thought that there’d be an easier way for something like this.
