### ISSUE TITLE
Is there a friendlier/consistent way to specify `lags` in `arx_args_list()`?

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epipredict#172]
@dshemetov notes that the int-vector or list-of-int-vectors-meant-to-be-lined-up-sequentially-with-the-`predictors`-from-`arx_forecaster()` format accepted by `arx_args_list()` could be unintuitive, and differs from how these are specified in `step_epi_lag`.  I don't know if there is a clear alternative, but we might seek something more consistent with `step_epi_lag`, or that enables us to use tidyselections instead of character vectors for `predictors`.

**Comment by dshemetov** [comment]
Vague idea: have the user feed `step_epi_lag` into `arx_args_list` and have `arx_forecaster` apply that step?

**Comment by dajmcdon** [comment]
`step_epi_lag()` applies the same lags to any columns selected by `...`. Because `...` obeys tidyselect syntax. There's no way to know how many columns are in `...`, so this step (like all other steps) must do the same operation to all columns. If you want to have different sets of lags for different sets of predictors, you have to call it multiple times. `arx_forecaster()` internally loops through to achieve the multiple calls. I'm not sure there's another way other than forcing the `arx_args_list()` to require `lags` to be a named list, with names corresponding to the predictors. Seems annoying.

**Comment by dshemetov** [comment]
Ah, if `lags` is a named list like `lags = list(confirmed_incidence_num = c(0, 7, 14), deaths_incidence_num = c(0, 7))`, then that seems good enough for me 👍. For context, I was coming to this function after reading `covidcast::aggregate_signals` where the lags list wasn't named, but was instead numbered, so it required you to keep the signals list in sync with the lags list, which is the kind of mental overhead I dislike having to maintain. But a named list is much better.

**Comment by dajmcdon** [comment]
TODO:

* Add functionality to `arx_args_list()` to check if the lags list is named. If so, validate and order correctly. If not, assume it's the same as the order of the predictors.
