### ISSUE TITLE
Profile the `full_join()` implementation for leads/lags

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/epipredict#18]
* Originally mentioned in #12 .

Examine `create_lags_and_leads()`. How slow is the [full join](https://github.com/cmu-delphi/epipredict/blob/50a6c9036935b6d9f26e46efbd2b9269f4c3d030/R/create_lags_and_leads.R#L47)? 

Is this something we should worry about?
Perhaps compare to `stats::embed()` or other more creative approaches.

**Comment by rachlobay** [comment]
Since this has been around for a while, I figured I could try a quick comparison... If anyone else wants to add stuff (ex. a more thorough comparison), please do.

The comparison here is on the four ex. given for this function and is between base R `merge`, dplyr `full_join` and base R merge where `xdat` and `ydat` are inputted as data tables… Note that the number of times each expression is evaluated is 1000, the output is in milliseconds, and that I’m using dplyr:1.0.9 and data.table:1.14.2 for these tests.

Here is the set-up of the comparison I am running using `microbenchmark()`:
 ```
bench_results <- microbenchmark(
    times = 1000L,
    base = merge(ydat, xdat, by = c("keys", "time_value"), all = TRUE),
    dplyr = dplyr::full_join(ydat, xdat, by = c("keys", "time_value")),
    DT = merge(dt_ydat, dt_xdat, by = c("keys", "time_value"), all = TRUE)
 )
```
And the results of the comparison for each ex. from the documentation of `bench_create_lags_and_leads()`:

```
> res1 <- bench_create_lags_and_leads(x, y, c(1, 2), 1, time_value)
> res1
Unit: milliseconds
  expr      min       lq     mean   median       uq      max neval cld
  base 1.151770 1.333166 1.640412 1.457447 1.660110 14.25975  1000 a  
 dplyr 1.505055 1.909237 2.352422 2.079852 2.393856 15.70226  1000  b 
    DT 2.146024 2.572112 3.134020 2.770401 3.181184 14.75390  1000   c
```

```
> res2 <- bench_create_lags_and_leads(x, y, list(c(1, 2), 1), 1, time_value)
> res2
Unit: milliseconds
  expr      min       lq     mean   median       uq       max neval cld
  base 1.036141 1.253363 1.466968 1.340394 1.489349  13.00170  1000 a  
 dplyr 1.462038 1.744002 2.248971 1.939192 2.141871 164.34910  1000  b 
    DT 1.996588 2.393236 2.808340 2.548910 2.791100  11.38263  1000   c
```
```
> res3 <- bench_create_lags_and_leads(x, y, list(c(-1, 1), NULL), 1, time_value)
> res3
Unit: milliseconds
  expr      min       lq     mean   median       uq      max neval cld
  base 1.010507 1.158149 1.362684 1.249379 1.369037 10.05419  1000 a  
 dplyr 1.494793 1.842852 2.188622 2.001017 2.228710 16.68774  1000  b 
    DT 2.104422 2.487208 2.925260 2.638247 2.980539 19.27696  1000   c
```
> res4 <- bench_create_lags_and_leads(x, y, c(1, 2), c(0, 1), time_value)
> res4
Unit: milliseconds
  expr      min       lq     mean   median       uq      max neval cld
  base 1.154777 1.330478 1.561372 1.431472 1.615312  8.98827  1000 a  
 dplyr 1.433345 1.800423 2.167596 1.989858 2.255216 24.02428  1000  b 
    DT 2.158531 2.493498 2.968385 2.673233 3.006118 16.20945  1000   c
```

Also, here’s side-by-side boxplots of the four sets of results for a visual comparison:
[create_lags_and_leads.pdf](https://github.com/cmu-delphi/epipredict/files/9099326/create_lags_and_leads.pdf)

So, overall, base seems to perform the best, followed by dplyr and then DT, but all three are fairly comparable.
