### ISSUE TITLE
post_add_forecast_date(), *_add_target_date()

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/epipredict#38]
Create a postprocessing step that adds the forecast date and the target date.

**Comment by brookslogan** [comment]
Sorry for the confusion when discussing this at the meeting.  From some more inspection of the `simple-forecasts.Rmd`:
- Yes, with `as_of=TRUE`, the forecast date is `time_value`, and the target date is `time_value+ahead`.  (Although, personally, I think it's a bit confusing that `epix_slide` calls the column that should be the forecast date the `time_value` rather than the `version`.  In fact, when we think about composability, I think it will be more natural to call the target date the `time_value`, because then we can think of performing backcasting on data signals and calibration on forecasts in the same sort of way.  May file another issue.)
- With `as_of=FALSE` I think this is also the assumption we are making, although it doesn't really make sense with real data sources without augmentation with nowcasts.
But:
- Note #50; I believe the above settings are what things "should" be, but they will be wrong / `arx_forecaster` will be suboptimal until this bug is fixed.
