### ISSUE TITLE
Intercept control

### ISSUE THREAD

**Issue by dajmcdon** [cmu-delphi/epipredict#71]
Is there a recipe step to remove the intercept term from a linear regression?

There is `step_intercept()` which "adds an intercept" as the first column of data. What if we want a no-intercept model?

**Comment by ChloeYou** [comment]
Digging through the packages, there doesn't seem to be a dedicated function that removes the intercept since it does depend on what model is being used. But some attempts:

1. using `step_intercept(value = 0)` after calling the recipe just adds an additional intercept column of zeros without getting rid of the `(Intercept)` term.

3. In the `parsnip` package, there seems to be an option to allow intercepts to be removed when we [set a model](https://www.tidymodels.org/learn/develop/models/). I'm wondering if this means we need to import and overwrite some model engines such as linear regression. Particularly, the ADD AN ENGINE section of the page has direct examples for linear regressions.

**Comment by ChloeYou** [comment]
Bookmarking the other useful page: https://parsnip.tidymodels.org/reference/set_new_model.html

**Comment by dajmcdon** [comment]
On conversation with @ChloeYou , intercept removal seems like very low priority.
